// import Script from "next/script";
import Script from "next/script";
import "./globals.css";
import AsyncScripts from "@/components/scripts/AsyncScripts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="deAT">
      <AsyncScripts />
      <body>
        <main className="flex min-h-screen flex-col items-center justify-between bg-white">
          {children}
        </main>
      </body>
    </html>
  );
}
